In [ ]:
import numpy as np
from utils import Utils

In [2]:
R_0 = np.array([[0.62802581, -0.66368827, -0.40632679], [-0.74459591, -0.36072926, -0.56165055], [0.22618692, 0.65528030, -0.72072686]])
R_1 = np.array([[-0.69694541, 0.71444254, 0.01607858], [-0.03785253, 0.56868150, -0.01722053], [-0.84238739, -0.33321527, 0.86689330]])
R_2 = np.array([[-0.03462962, -0.82574949, -0.25034989], [0.74003479, -0.36703212, -0.17310211], [0.54139482, -0.44531970, -0.64714007]])
R_3 = np.array([[0.62802581, -0.74459591, 0.22618692], [-0.66368827, -0.36072926, 0.65528030], [-0.40632679, -0.56165055, -0.72072686]])

In [9]:
print(R_1)

[[-0.69694541  0.71444254  0.01607858]
 [-0.03785253  0.5686815  -0.01722053]
 [-0.84238739 -0.33321527  0.8668933 ]]


In [3]:
print(Utils().is_rotation_matrix(R_3))

True


In [16]:
print(np.linalg.inv(R_3))

[[ 0.62802581 -0.66368828 -0.40632679]
 [-0.7445959  -0.36072926 -0.56165054]
 [ 0.22618692  0.65528031 -0.72072685]]


In [17]:
print(R_0)

[[ 0.62802581 -0.66368827 -0.40632679]
 [-0.74459591 -0.36072926 -0.56165055]
 [ 0.22618692  0.6552803  -0.72072686]]


In [18]:
print(R_0@R_3)

[[ 9.99999998e-01 -5.90942242e-09  6.46290360e-09]
 [-5.90942242e-09  1.00000001e+00  4.07969775e-09]
 [ 6.46290360e-09  4.07969775e-09  1.00000000e+00]]


In [4]:
utils = Utils(radians=False)

In [10]:
print(utils.rotation_matrix_2d(30))

[[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]


In [11]:
import numpy as np

R1 = np.array([[0.95886376, -0.10709918, 0.35470994], [-0.07327819, 0.95377089, 0.55189139], [-0.38968703, -0.38673707, 0.69155479]])
R2 = np.array([[0.52498888, -0.36130326, 0.77061445], [0.58862909, 0.80810025, -0.02213100], [-0.61473773, 0.46522461, 0.63691725]])
R3 = np.array([[0.05007299, -0.48318452, -1.06681360], [0.98462005, -0.26138168, 0.10022485], [-0.44397290, -1.01400812, 0.29167828]])
R4 = np.array([[-0.53376369, 0.29725642, -1.12663754], [-0.06448341, -1.04313459, -0.20270837], [-0.91820193, -0.12894428, 0.33887770]])
R5 = np.array([[0.34823471, 0.33733891, 0.97556691], [0.49368834, 0.77047807, -0.29278726], [-0.91870795, 0.62585926, 0.03628586]])

In [17]:
print(utils.is_rotation_matrix(R2))

True


In [28]:
import numpy as np

R_67 = np.array([[0.03836700, -0.83366882, -0.55093036], [0.66824096, -0.38851438, 0.63443723], [-0.74295491, -0.39249569, 0.54218552]])
p_7 = np.array([[-0.06418931], [0.82033795], [0.25627231]])

In [26]:
R_62 = np.transpose(R_26)

In [29]:
print(R_67@p_7)

[[-0.82754112]
 [-0.19901832]
 [-0.13534221]]
