In [1]:
import numpy as np
from utils import Utils
import scipy

In [59]:
import numpy as np

theta = np.array([0.70,0.54,-0.27])

In [60]:
T_0_j1 = Utils.homogeneous_matrix(None,Utils.translation(theta[0],0.0,2.0))
T_j1_j2 = Utils.homogeneous_matrix(None,Utils.translation(0.0,-2.0,-2.0-theta[1]))
T_j2_j3 = Utils.homogeneous_matrix(None,Utils.translation(0.0,-2.0,theta[2]-2.0))
T_j3_final = Utils.homogeneous_matrix(Utils.rotation_matrix_x(np.pi/2),Utils.translation(0.0,0.0,2.0))

In [61]:
T_j1_final = T_j1_j2 @ T_j2_j3 @ T_j3_final
V_j1 = Utils.adjoint(Utils.inverse_homogeneous_matrix(T_j1_final)) @ Utils.to_twist_vector(np.array([1.0,0.0,0.0]),np.array([0.0,0.0,0.0]))
print(V_j1)

[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]]


In [62]:
T_j2_final = T_j2_j3 @ T_j3_final
V_j2 = Utils.adjoint(Utils.inverse_homogeneous_matrix(T_j2_final)) @ Utils.to_twist_vector(np.array([0.0,0.0,-1.0]),np.array([0.0,0.0,0.0]))
print(V_j2)

[[ 0.000000e+00]
 [ 0.000000e+00]
 [ 0.000000e+00]
 [ 0.000000e+00]
 [-1.000000e+00]
 [-6.123234e-17]]


In [63]:
T_j3_final = T_j3_final
V_j3 = Utils.adjoint(Utils.inverse_homogeneous_matrix(T_j3_final)) @ Utils.to_twist_vector(np.array([0.0,0.0,1.0]),np.array([0.0,0.0,0.0]))
print(V_j3)

[[0.000000e+00]
 [0.000000e+00]
 [0.000000e+00]
 [0.000000e+00]
 [1.000000e+00]
 [6.123234e-17]]


In [64]:
a = []  
a = print(np.array(np.block([V_j1,V_j2,V_j3])))

[[ 0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00]
 [ 1.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00 -1.000000e+00  1.000000e+00]
 [ 0.000000e+00 -6.123234e-17  6.123234e-17]]
